import { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { getItem, getMatches, deleteItem } from "../api/api";
import MatchBadge from "../components/MatchBadge";

export default function ItemDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [item, setItem] = useState(null);
  const [matches, setMatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const [matchesLoading, setMatchesLoading] = useState(true);
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState(false);

  useEffect(() => {
    setLoading(true);
    setError("");
    getItem(id)
      .then(setItem)
      .catch(() => setError("Item not found."))
      .finally(() => setLoading(false));
  }, [id]);

  useEffect(() => {
    setMatchesLoading(true);
    getMatches(id)
      .then(setMatches)
      .catch(() => setMatches([]))
      .finally(() => setMatchesLoading(false));
  }, [id]);

  if (loading) return <div className="container">Loading...</div>;
  if (error) return <div className="container error-text">{error}</div>;
  if (!item) return null;

  const oppositeLabel = item.type === "lost" ? "Found" : "Lost";
  const currentStudentId = localStorage.getItem("studentId");
  const currentRole = localStorage.getItem("studentRole");
  const canDelete =
    (item.reportedBy && item.reportedBy === currentStudentId) || currentRole === "admin";

  async function handleDelete() {
    if (!window.confirm("Delete this report permanently? This can't be undone.")) return;
    setDeleting(true);
    try {
      await deleteItem(id);
      navigate("/");
    } catch (err) {
      alert("Failed to delete: " + (err.response?.data?.message || err.message));
      setDeleting(false);
    }
  }

  return (
    <div className="container narrow">
      <Link to="/" className="back-link">
        &larr; Back to browse
      </Link>

      <div className="item-detail">
        <div className="item-detail-image">
          {item.imageUrl ? (
            <img src={item.imageUrl} alt={item.title} />
          ) : (
            <div className="item-card-noimage large">No image provided</div>
          )}
        </div>

        <div className="item-detail-info">
          <div className="item-card-tags">
            <span className={`tag tag-${item.type}`}>{item.type}</span>
            <span className="tag tag-category">{item.category}</span>
            <span className={`tag tag-status-${item.status}`}>{item.status}</span>
          </div>
          <h1>{item.title}</h1>
          <p>{item.description}</p>
          <ul className="detail-meta-list">
            <li>
              <strong>Location:</strong> {item.location}
            </li>
            <li>
              <strong>Date {item.type}:</strong> {new Date(item.date).toLocaleDateString()}
            </li>
            <li>
              <strong>Reported by:</strong> {item.reporterName}
            </li>
            <li>
              <strong>Contact:</strong> {item.reporterContact}
            </li>
          </ul>

          {canDelete && (
            <button
              className="link-button danger"
              onClick={handleDelete}
              disabled={deleting}
              style={{ marginTop: "1rem" }}
            >
              {deleting ? "Deleting..." : "Delete this report"}
            </button>
          )}
        </div>
      </div>

      <section className="matches-section">
        <h2>
          Possible {oppositeLabel} Item Matches{" "}
          <span className="matches-hint">(auto-generated by keyword similarity)</span>
        </h2>

        {matchesLoading && <p>Calculating matches...</p>}
        {!matchesLoading && matches.length === 0 && (
          <p>No strong matches yet. Check back later as more items get reported.</p>
        )}

        <div className="matches-list">
          {matches.map(({ item: candidate, matchScore, matchBreakdown }) => (
            <Link to={`/items/${candidate._id}`} key={candidate._id} className="match-card">
              <div className="match-card-header">
                <strong>{candidate.title}</strong>
                <MatchBadge score={matchScore} />
              </div>
              <p className="item-card-desc">{candidate.description}</p>
              <div className="match-breakdown">
                <span>Text similarity: {matchBreakdown.textSimilarity}%</span>
                <span>Category match: {matchBreakdown.categoryMatch}%</span>
                <span>Location similarity: {matchBreakdown.locationSimilarity}%</span>
              </div>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}